const FALLBACK_REPORT={reportDate:"2026-08-13",cutoffLabel:"Monday, Aug 17",summary:"Fresh FOC Heat research.",books:[]};
const PURCHASE_KEY="focHeatPurchases.v1";let REPORT=FALLBACK_REPORT,WATCH=[],PURCHASES={};
function esc(s){return String(s??"").replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]))}
function showStatus(m,e=false){const s=document.querySelector('#status');s.hidden=false;s.className=`status ${e?'error':''}`;s.textContent=m;if(!e)setTimeout(()=>s.hidden=true,7000)}
function apiBase(){return String(window.FOC_API_BASE||'').replace(/\/$/,'')}
function token(){return window.FOC_CLIENT_TOKEN||localStorage.getItem('focHeatClientToken')||''}
function headers(){const t=token();return t?{Authorization:`Bearer ${t}`}:{}}
function loadLocalPurchases(){try{PURCHASES=JSON.parse(localStorage.getItem(PURCHASE_KEY)||'{}')||{}}catch(e){PURCHASES={}}}
function saveLocalPurchases(){localStorage.setItem(PURCHASE_KEY,JSON.stringify(PURCHASES))}
function purchaseForm(b){const p=PURCHASES[b.title]||{},c=p.purchased?'checked':'';return `<div class="purchase-box"><div class="purchase-head"><strong>Your Purchase</strong><label class="switch"><input type="checkbox" class="purchase-toggle" data-title="${esc(b.title)}" ${c}><span>Purchased</span></label></div><div class="purchase-fields ${c?'':'hidden'}"><label>Quantity<input type="number" min="1" step="1" class="purchase-qty" value="${esc(p.quantity||'')}"></label><label>Price / copy<input type="number" min="0" step="0.01" class="purchase-price" value="${esc(p.pricePerCopy??'')}"></label><label>Price basis<select class="purchase-basis"><option ${p.priceBasis==='Cover Price'?'selected':''}>Cover Price</option><option ${p.priceBasis==='Discounted'?'selected':''}>Discounted</option><option ${p.priceBasis==='Premium'?'selected':''}>Premium</option><option ${p.priceBasis==='Unknown'?'selected':''}>Unknown</option></select></label><label>Purchase date<input type="date" class="purchase-date" value="${esc(p.purchaseDate||'')}"></label><label>Retailer / source<input type="text" class="purchase-retailer" value="${esc(p.retailer||'')}" placeholder="Optional"></label><button type="button" class="save-purchase" data-title="${esc(b.title)}">Save purchase</button></div></div>`}
function renderBook(b){const facts=(b.verifiedFacts||[]).map(x=>`<li>${esc(x)}</li>`).join(''),ev=(b.marketEvidence||[]).map(x=>`<li>${esc(x)}</li>`).join(''),un=(b.unknowns||[]).map(x=>`<li>${esc(x)}</li>`).join(''),src=(b.sources||[]).map(u=>`<a href="${esc(u)}" target="_blank" rel="noopener">Source</a>`).join(' ');return `<article class="book"><div class="book-top"><div><div class="rank">#${esc(b.rank)}</div><h3>${esc(b.title)}</h3><div class="publisher">${esc(b.publisher)}</div></div><span class="badge ${(b.action||'').toLowerCase().replace(/[^a-z-]/g,'-')}">${esc(b.action)}</span></div><div class="book-grid"><div class="metric"><span>Evidence</span><strong>${esc(b.evidenceGrade||'—')}</strong></div><div class="metric"><span>Confidence</span><strong>${esc(b.confidence)}</strong></div><div class="metric"><span>Buy</span><strong>${esc(b.qty)}</strong></div><div class="metric"><span>Max price</span><strong>${b.maximumAcquisitionPrice==null?'—':'$'+Number(b.maximumAcquisitionPrice).toFixed(2)}</strong></div></div><div class="dates"><span>FOC ${esc(b.foc||'Unknown')}</span><span>Release ${esc(b.releaseDate||'Unknown')}</span></div><div class="creators"><strong>Creators:</strong> ${esc(b.creators||'Not recorded')}</div><details><summary>Research evidence</summary><div class="evidence"><h4>Verified facts</h4><ul>${facts||'<li>None recorded.</li>'}</ul><h4>Market evidence</h4><ul>${ev||'<li>None recorded.</li>'}</ul><h4>Investment thesis</h4><p>${esc(b.thesis||'')}</p><h4>Unknowns</h4><ul>${un||'<li>None recorded.</li>'}</ul><div class="sources">${src}</div></div></details>${purchaseForm(b)}</article>`}
function render(r,w){REPORT=r||FALLBACK_REPORT;WATCH=w||[];document.querySelector('#reportTitle').textContent=`FOC Heat — ${REPORT.reportDate||'Current'}`;document.querySelector('#reportMeta').textContent=REPORT.summary||'Investment first.';document.querySelector('#cutoff').textContent=REPORT.cutoffLabel||'—';document.querySelector('#report').innerHTML=(REPORT.books||[]).map(renderBook).join('')||'<div class="empty">No report available.</div>';document.querySelector('#watchCount').textContent=WATCH.length;document.querySelector('#watchlist').innerHTML=WATCH.map(x=>`<div class="watch-item"><strong>${esc(x.title)}</strong><span>${esc(x.status||'')} ${esc(x.reason||'')}</span></div>`).join('')||'<div class="empty">No watchlist items.</div>';document.querySelector('#ledger').innerHTML=(REPORT.ledgerNotes||[]).map(x=>`<div class="ledger-item"><strong>${esc(x)}</strong></div>`).join('')||'<div class="empty">No ledger entries.</div>';bindPurchaseUI()}
async function apiGet(path){const r=await fetch(`${apiBase()}${path}`,{headers:headers(),cache:'no-store'});if(!r.ok)throw Error(r.status);return r.json()}
async function loadPurchases(){loadLocalPurchases();if(!apiBase())return;try{const p=await apiGet('/api/purchases');if(p&&typeof p==='object')PURCHASES=p;saveLocalPurchases()}catch(e){}}
async function savePurchase(title,box){const d={purchased:true,quantity:Number(box.querySelector('.purchase-qty').value||0),pricePerCopy:Number(box.querySelector('.purchase-price').value||0),priceBasis:box.querySelector('.purchase-basis').value,purchaseDate:box.querySelector('.purchase-date').value,retailer:box.querySelector('.purchase-retailer').value};if(!d.quantity||d.pricePerCopy<0||!d.purchaseDate){showStatus('Enter quantity, price, and purchase date.',true);return}PURCHASES[title]=d;saveLocalPurchases();if(apiBase()){try{await fetch(`${apiBase()}/api/purchases`,{method:'POST',headers:{'Content-Type':'application/json',...headers()},body:JSON.stringify({title,purchase:d})});showStatus('Purchase saved to the project ledger.')}catch(e){showStatus('Saved on this device; Worker persistence was unavailable.',true)}}else showStatus('Purchase saved on this device. Deploy the optional Worker to sync it across devices.')}
function bindPurchaseUI(){document.querySelectorAll('.purchase-toggle').forEach(t=>t.addEventListener('change',()=>{const box=t.closest('.purchase-box');box.querySelector('.purchase-fields').classList.toggle('hidden',!t.checked);if(!t.checked){delete PURCHASES[t.dataset.title];saveLocalPurchases()}}));document.querySelectorAll('.save-purchase').forEach(b=>b.addEventListener('click',()=>savePurchase(b.dataset.title,b.closest('.purchase-box'))))}
async function loadData(){await loadPurchases();try{let r,w;if(apiBase()){try{r=await apiGet('/api/report');w=await apiGet('/api/watchlist')}catch(e){r=await fetch('data/current.json',{cache:'no-store'}).then(x=>x.json());w=await fetch('data/watchlist.json',{cache:'no-store'}).then(x=>x.json())}}else{[r,w]=await Promise.all([fetch('data/current.json',{cache:'no-store'}).then(x=>x.ok?x.json():FALLBACK_REPORT),fetch('data/watchlist.json',{cache:'no-store'}).then(x=>x.ok?x.json():[])]);}render(r,w)}catch(e){render(FALLBACK_REPORT,[]);showStatus('Unable to load the current report.',true)}}
function buildResearchPrompt(){const today=new Date().toISOString().slice(0,10);return `I am continuing my FOC Heat comic-book investment research project. The canonical repository is https://github.com/mmzeller/foc. Today is ${today}.\n\nBEFORE RESEARCHING: inspect the repository and read PROJECT_CONTEXT.md, data/predictions.json, data/watchlist.json, data/current.json, and research-prompt.md. Treat those files as the project's source of truth.\n\nRUN THIS WEEK'S FOC HEAT REPORT. Re-research the current FOC window from fresh sources. Preserve historical predictions.\n\nPurchase records, if present in the app, are user actions and must never be assumed. Distinguish AI predictions from user purchases. Never change a historical prediction merely because the user did or did not purchase it.\n\nInvestment first. Verify the next FOC cutoff. Never recommend a passed FOC as a current BUY. Separate verified facts, market evidence, investment thesis and unknowns. Never fabricate print runs, orders, sales, scarcity or first appearances. Distinguish asking prices from completed sales. Demand-versus-supply evidence outweighs creator hype. Acquisition price matters. Use conservative conviction language and PASS/WATCH when evidence is weak.\n\nFor every serious candidate include title, publisher, release date, exact FOC date, creators, verified facts, market evidence, thesis, unknowns, risk, confidence, suggested quantity, maximum acquisition price if supportable, and source links. End with the actual shopping list.\n\nAfter completing the report, update the repository's current report, prediction ledger, watchlist, and archived report without rewriting history.`}
async function requestResearch(){const p=buildResearchPrompt();try{await navigator.clipboard.writeText(p)}catch(e){}const u=`https://chatgpt.com/?q=${encodeURIComponent(p)}`;try{window.open(u,'_blank','noopener')}catch(e){window.location.href=u}showStatus('Research prompt copied/opened. Run the report in ChatGPT, then update the repository.')}
document.querySelector('#refreshBtn').addEventListener('click',requestResearch);document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const id=b.dataset.target;if(id==='top')window.scrollTo({top:0,behavior:'smooth'});else document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})}));loadData();